apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: arkmq-org-broker-operator-catalog-source
  namespace: operators
spec:
  displayName: ArkMQ Broker Operator Catalog
  image: arkmq-org-broker-operator-catalog:latest
  sourceType: grpc
