//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	"k8s.io/api/core/v1"
	policyv1 "k8s.io/api/policy/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceptorType) DeepCopyInto(out *AcceptorType) {
	*out = *in
	if in.ExposeMode != nil {
		in, out := &in.ExposeMode, &out.ExposeMode
		*out = new(ExposeMode)
		**out = **in
	}
	if in.SupportAdvisory != nil {
		in, out := &in.SupportAdvisory, &out.SupportAdvisory
		*out = new(bool)
		**out = **in
	}
	if in.SuppressInternalManagementObjects != nil {
		in, out := &in.SuppressInternalManagementObjects, &out.SuppressInternalManagementObjects
		*out = new(bool)
		**out = **in
	}
	if in.BindToAllInterfaces != nil {
		in, out := &in.BindToAllInterfaces, &out.BindToAllInterfaces
		*out = new(bool)
		**out = **in
	}
	if in.TrustSecret != nil {
		in, out := &in.TrustSecret, &out.TrustSecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceptorType.
func (in *AcceptorType) DeepCopy() *AcceptorType {
	if in == nil {
		return nil
	}
	out := new(AcceptorType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressSettingType) DeepCopyInto(out *AddressSettingType) {
	*out = *in
	if in.DeadLetterAddress != nil {
		in, out := &in.DeadLetterAddress, &out.DeadLetterAddress
		*out = new(string)
		**out = **in
	}
	if in.AutoCreateDeadLetterResources != nil {
		in, out := &in.AutoCreateDeadLetterResources, &out.AutoCreateDeadLetterResources
		*out = new(bool)
		**out = **in
	}
	if in.DeadLetterQueuePrefix != nil {
		in, out := &in.DeadLetterQueuePrefix, &out.DeadLetterQueuePrefix
		*out = new(string)
		**out = **in
	}
	if in.DeadLetterQueueSuffix != nil {
		in, out := &in.DeadLetterQueueSuffix, &out.DeadLetterQueueSuffix
		*out = new(string)
		**out = **in
	}
	if in.ExpiryAddress != nil {
		in, out := &in.ExpiryAddress, &out.ExpiryAddress
		*out = new(string)
		**out = **in
	}
	if in.AutoCreateExpiryResources != nil {
		in, out := &in.AutoCreateExpiryResources, &out.AutoCreateExpiryResources
		*out = new(bool)
		**out = **in
	}
	if in.ExpiryQueuePrefix != nil {
		in, out := &in.ExpiryQueuePrefix, &out.ExpiryQueuePrefix
		*out = new(string)
		**out = **in
	}
	if in.ExpiryQueueSuffix != nil {
		in, out := &in.ExpiryQueueSuffix, &out.ExpiryQueueSuffix
		*out = new(string)
		**out = **in
	}
	if in.ExpiryDelay != nil {
		in, out := &in.ExpiryDelay, &out.ExpiryDelay
		*out = new(int32)
		**out = **in
	}
	if in.MinExpiryDelay != nil {
		in, out := &in.MinExpiryDelay, &out.MinExpiryDelay
		*out = new(int32)
		**out = **in
	}
	if in.MaxExpiryDelay != nil {
		in, out := &in.MaxExpiryDelay, &out.MaxExpiryDelay
		*out = new(int32)
		**out = **in
	}
	if in.RedeliveryDelay != nil {
		in, out := &in.RedeliveryDelay, &out.RedeliveryDelay
		*out = new(int32)
		**out = **in
	}
	if in.MaxRedeliveryDelay != nil {
		in, out := &in.MaxRedeliveryDelay, &out.MaxRedeliveryDelay
		*out = new(int32)
		**out = **in
	}
	if in.MaxDeliveryAttempts != nil {
		in, out := &in.MaxDeliveryAttempts, &out.MaxDeliveryAttempts
		*out = new(int32)
		**out = **in
	}
	if in.MaxSizeBytes != nil {
		in, out := &in.MaxSizeBytes, &out.MaxSizeBytes
		*out = new(string)
		**out = **in
	}
	if in.MaxSizeBytesRejectThreshold != nil {
		in, out := &in.MaxSizeBytesRejectThreshold, &out.MaxSizeBytesRejectThreshold
		*out = new(int32)
		**out = **in
	}
	if in.PageSizeBytes != nil {
		in, out := &in.PageSizeBytes, &out.PageSizeBytes
		*out = new(string)
		**out = **in
	}
	if in.PageMaxCacheSize != nil {
		in, out := &in.PageMaxCacheSize, &out.PageMaxCacheSize
		*out = new(int32)
		**out = **in
	}
	if in.AddressFullPolicy != nil {
		in, out := &in.AddressFullPolicy, &out.AddressFullPolicy
		*out = new(string)
		**out = **in
	}
	if in.MessageCounterHistoryDayLimit != nil {
		in, out := &in.MessageCounterHistoryDayLimit, &out.MessageCounterHistoryDayLimit
		*out = new(int32)
		**out = **in
	}
	if in.LastValueQueue != nil {
		in, out := &in.LastValueQueue, &out.LastValueQueue
		*out = new(bool)
		**out = **in
	}
	if in.DefaultLastValueQueue != nil {
		in, out := &in.DefaultLastValueQueue, &out.DefaultLastValueQueue
		*out = new(bool)
		**out = **in
	}
	if in.DefaultLastValueKey != nil {
		in, out := &in.DefaultLastValueKey, &out.DefaultLastValueKey
		*out = new(string)
		**out = **in
	}
	if in.DefaultNonDestructive != nil {
		in, out := &in.DefaultNonDestructive, &out.DefaultNonDestructive
		*out = new(bool)
		**out = **in
	}
	if in.DefaultExclusiveQueue != nil {
		in, out := &in.DefaultExclusiveQueue, &out.DefaultExclusiveQueue
		*out = new(bool)
		**out = **in
	}
	if in.DefaultGroupRebalance != nil {
		in, out := &in.DefaultGroupRebalance, &out.DefaultGroupRebalance
		*out = new(bool)
		**out = **in
	}
	if in.DefaultGroupRebalancePauseDispatch != nil {
		in, out := &in.DefaultGroupRebalancePauseDispatch, &out.DefaultGroupRebalancePauseDispatch
		*out = new(bool)
		**out = **in
	}
	if in.DefaultGroupBuckets != nil {
		in, out := &in.DefaultGroupBuckets, &out.DefaultGroupBuckets
		*out = new(int32)
		**out = **in
	}
	if in.DefaultGroupFirstKey != nil {
		in, out := &in.DefaultGroupFirstKey, &out.DefaultGroupFirstKey
		*out = new(string)
		**out = **in
	}
	if in.DefaultConsumersBeforeDispatch != nil {
		in, out := &in.DefaultConsumersBeforeDispatch, &out.DefaultConsumersBeforeDispatch
		*out = new(int32)
		**out = **in
	}
	if in.DefaultDelayBeforeDispatch != nil {
		in, out := &in.DefaultDelayBeforeDispatch, &out.DefaultDelayBeforeDispatch
		*out = new(int32)
		**out = **in
	}
	if in.RedistributionDelay != nil {
		in, out := &in.RedistributionDelay, &out.RedistributionDelay
		*out = new(int32)
		**out = **in
	}
	if in.SendToDlaOnNoRoute != nil {
		in, out := &in.SendToDlaOnNoRoute, &out.SendToDlaOnNoRoute
		*out = new(bool)
		**out = **in
	}
	if in.SlowConsumerThreshold != nil {
		in, out := &in.SlowConsumerThreshold, &out.SlowConsumerThreshold
		*out = new(int32)
		**out = **in
	}
	if in.SlowConsumerPolicy != nil {
		in, out := &in.SlowConsumerPolicy, &out.SlowConsumerPolicy
		*out = new(string)
		**out = **in
	}
	if in.SlowConsumerCheckPeriod != nil {
		in, out := &in.SlowConsumerCheckPeriod, &out.SlowConsumerCheckPeriod
		*out = new(int32)
		**out = **in
	}
	if in.AutoCreateJmsQueues != nil {
		in, out := &in.AutoCreateJmsQueues, &out.AutoCreateJmsQueues
		*out = new(bool)
		**out = **in
	}
	if in.AutoDeleteJmsQueues != nil {
		in, out := &in.AutoDeleteJmsQueues, &out.AutoDeleteJmsQueues
		*out = new(bool)
		**out = **in
	}
	if in.AutoCreateJmsTopics != nil {
		in, out := &in.AutoCreateJmsTopics, &out.AutoCreateJmsTopics
		*out = new(bool)
		**out = **in
	}
	if in.AutoDeleteJmsTopics != nil {
		in, out := &in.AutoDeleteJmsTopics, &out.AutoDeleteJmsTopics
		*out = new(bool)
		**out = **in
	}
	if in.AutoCreateQueues != nil {
		in, out := &in.AutoCreateQueues, &out.AutoCreateQueues
		*out = new(bool)
		**out = **in
	}
	if in.AutoDeleteQueues != nil {
		in, out := &in.AutoDeleteQueues, &out.AutoDeleteQueues
		*out = new(bool)
		**out = **in
	}
	if in.AutoDeleteCreatedQueues != nil {
		in, out := &in.AutoDeleteCreatedQueues, &out.AutoDeleteCreatedQueues
		*out = new(bool)
		**out = **in
	}
	if in.AutoDeleteQueuesDelay != nil {
		in, out := &in.AutoDeleteQueuesDelay, &out.AutoDeleteQueuesDelay
		*out = new(int32)
		**out = **in
	}
	if in.AutoDeleteQueuesMessageCount != nil {
		in, out := &in.AutoDeleteQueuesMessageCount, &out.AutoDeleteQueuesMessageCount
		*out = new(int32)
		**out = **in
	}
	if in.ConfigDeleteQueues != nil {
		in, out := &in.ConfigDeleteQueues, &out.ConfigDeleteQueues
		*out = new(string)
		**out = **in
	}
	if in.AutoCreateAddresses != nil {
		in, out := &in.AutoCreateAddresses, &out.AutoCreateAddresses
		*out = new(bool)
		**out = **in
	}
	if in.AutoDeleteAddresses != nil {
		in, out := &in.AutoDeleteAddresses, &out.AutoDeleteAddresses
		*out = new(bool)
		**out = **in
	}
	if in.AutoDeleteAddressesDelay != nil {
		in, out := &in.AutoDeleteAddressesDelay, &out.AutoDeleteAddressesDelay
		*out = new(int32)
		**out = **in
	}
	if in.ConfigDeleteAddresses != nil {
		in, out := &in.ConfigDeleteAddresses, &out.ConfigDeleteAddresses
		*out = new(string)
		**out = **in
	}
	if in.ManagementBrowsePageSize != nil {
		in, out := &in.ManagementBrowsePageSize, &out.ManagementBrowsePageSize
		*out = new(int32)
		**out = **in
	}
	if in.DefaultPurgeOnNoConsumers != nil {
		in, out := &in.DefaultPurgeOnNoConsumers, &out.DefaultPurgeOnNoConsumers
		*out = new(bool)
		**out = **in
	}
	if in.DefaultMaxConsumers != nil {
		in, out := &in.DefaultMaxConsumers, &out.DefaultMaxConsumers
		*out = new(int32)
		**out = **in
	}
	if in.DefaultQueueRoutingType != nil {
		in, out := &in.DefaultQueueRoutingType, &out.DefaultQueueRoutingType
		*out = new(string)
		**out = **in
	}
	if in.DefaultAddressRoutingType != nil {
		in, out := &in.DefaultAddressRoutingType, &out.DefaultAddressRoutingType
		*out = new(string)
		**out = **in
	}
	if in.DefaultConsumerWindowSize != nil {
		in, out := &in.DefaultConsumerWindowSize, &out.DefaultConsumerWindowSize
		*out = new(int32)
		**out = **in
	}
	if in.DefaultRingSize != nil {
		in, out := &in.DefaultRingSize, &out.DefaultRingSize
		*out = new(int32)
		**out = **in
	}
	if in.RetroactiveMessageCount != nil {
		in, out := &in.RetroactiveMessageCount, &out.RetroactiveMessageCount
		*out = new(int32)
		**out = **in
	}
	if in.EnableMetrics != nil {
		in, out := &in.EnableMetrics, &out.EnableMetrics
		*out = new(bool)
		**out = **in
	}
	if in.ManagementMessageAttributeSizeLimit != nil {
		in, out := &in.ManagementMessageAttributeSizeLimit, &out.ManagementMessageAttributeSizeLimit
		*out = new(int32)
		**out = **in
	}
	if in.SlowConsumerThresholdMeasurementUnit != nil {
		in, out := &in.SlowConsumerThresholdMeasurementUnit, &out.SlowConsumerThresholdMeasurementUnit
		*out = new(string)
		**out = **in
	}
	if in.EnableIngressTimestamp != nil {
		in, out := &in.EnableIngressTimestamp, &out.EnableIngressTimestamp
		*out = new(bool)
		**out = **in
	}
	if in.ConfigDeleteDiverts != nil {
		in, out := &in.ConfigDeleteDiverts, &out.ConfigDeleteDiverts
		*out = new(string)
		**out = **in
	}
	if in.MaxSizeMessages != nil {
		in, out := &in.MaxSizeMessages, &out.MaxSizeMessages
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressSettingType.
func (in *AddressSettingType) DeepCopy() *AddressSettingType {
	if in == nil {
		return nil
	}
	out := new(AddressSettingType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressSettingsType) DeepCopyInto(out *AddressSettingsType) {
	*out = *in
	if in.ApplyRule != nil {
		in, out := &in.ApplyRule, &out.ApplyRule
		*out = new(string)
		**out = **in
	}
	if in.AddressSetting != nil {
		in, out := &in.AddressSetting, &out.AddressSetting
		*out = make([]AddressSettingType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressSettingsType.
func (in *AddressSettingsType) DeepCopy() *AddressSettingsType {
	if in == nil {
		return nil
	}
	out := new(AddressSettingsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AffinityConfig) DeepCopyInto(out *AffinityConfig) {
	*out = *in
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(v1.NodeAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAffinity != nil {
		in, out := &in.PodAffinity, &out.PodAffinity
		*out = new(v1.PodAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAntiAffinity != nil {
		in, out := &in.PodAntiAffinity, &out.PodAntiAffinity
		*out = new(v1.PodAntiAffinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AffinityConfig.
func (in *AffinityConfig) DeepCopy() *AffinityConfig {
	if in == nil {
		return nil
	}
	out := new(AffinityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppAcceptorType) DeepCopyInto(out *AppAcceptorType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppAcceptorType.
func (in *AppAcceptorType) DeepCopy() *AppAcceptorType {
	if in == nil {
		return nil
	}
	out := new(AppAcceptorType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppAddressType) DeepCopyInto(out *AppAddressType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppAddressType.
func (in *AppAddressType) DeepCopy() *AppAddressType {
	if in == nil {
		return nil
	}
	out := new(AppAddressType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppCapabilityType) DeepCopyInto(out *AppCapabilityType) {
	*out = *in
	if in.ProducerOf != nil {
		in, out := &in.ProducerOf, &out.ProducerOf
		*out = make([]AppAddressType, len(*in))
		copy(*out, *in)
	}
	if in.ConsumerOf != nil {
		in, out := &in.ConsumerOf, &out.ConsumerOf
		*out = make([]AppAddressType, len(*in))
		copy(*out, *in)
	}
	if in.SubscriberOf != nil {
		in, out := &in.SubscriberOf, &out.SubscriberOf
		*out = make([]AppAddressType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppCapabilityType.
func (in *AppCapabilityType) DeepCopy() *AppCapabilityType {
	if in == nil {
		return nil
	}
	out := new(AppCapabilityType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Broker) DeepCopyInto(out *Broker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Broker.
func (in *Broker) DeepCopy() *Broker {
	if in == nil {
		return nil
	}
	out := new(Broker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Broker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerApp) DeepCopyInto(out *BrokerApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerApp.
func (in *BrokerApp) DeepCopy() *BrokerApp {
	if in == nil {
		return nil
	}
	out := new(BrokerApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BrokerApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerAppList) DeepCopyInto(out *BrokerAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BrokerApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerAppList.
func (in *BrokerAppList) DeepCopy() *BrokerAppList {
	if in == nil {
		return nil
	}
	out := new(BrokerAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BrokerAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerAppSpec) DeepCopyInto(out *BrokerAppSpec) {
	*out = *in
	if in.ServiceSelector != nil {
		in, out := &in.ServiceSelector, &out.ServiceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Acceptor = in.Acceptor
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]AppCapabilityType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerAppSpec.
func (in *BrokerAppSpec) DeepCopy() *BrokerAppSpec {
	if in == nil {
		return nil
	}
	out := new(BrokerAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerAppStatus) DeepCopyInto(out *BrokerAppStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Binding != nil {
		in, out := &in.Binding, &out.Binding
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerAppStatus.
func (in *BrokerAppStatus) DeepCopy() *BrokerAppStatus {
	if in == nil {
		return nil
	}
	out := new(BrokerAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerList) DeepCopyInto(out *BrokerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Broker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerList.
func (in *BrokerList) DeepCopy() *BrokerList {
	if in == nil {
		return nil
	}
	out := new(BrokerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BrokerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerService) DeepCopyInto(out *BrokerService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerService.
func (in *BrokerService) DeepCopy() *BrokerService {
	if in == nil {
		return nil
	}
	out := new(BrokerService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BrokerService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerServiceList) DeepCopyInto(out *BrokerServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BrokerService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerServiceList.
func (in *BrokerServiceList) DeepCopy() *BrokerServiceList {
	if in == nil {
		return nil
	}
	out := new(BrokerServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BrokerServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerServiceSpec) DeepCopyInto(out *BrokerServiceSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerServiceSpec.
func (in *BrokerServiceSpec) DeepCopy() *BrokerServiceSpec {
	if in == nil {
		return nil
	}
	out := new(BrokerServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerServiceStatus) DeepCopyInto(out *BrokerServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProvisionedApps != nil {
		in, out := &in.ProvisionedApps, &out.ProvisionedApps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerServiceStatus.
func (in *BrokerServiceStatus) DeepCopy() *BrokerServiceStatus {
	if in == nil {
		return nil
	}
	out := new(BrokerServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerSpec) DeepCopyInto(out *BrokerSpec) {
	*out = *in
	in.DeploymentPlan.DeepCopyInto(&out.DeploymentPlan)
	if in.Acceptors != nil {
		in, out := &in.Acceptors, &out.Acceptors
		*out = make([]AcceptorType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Connectors != nil {
		in, out := &in.Connectors, &out.Connectors
		*out = make([]ConnectorType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Console.DeepCopyInto(&out.Console)
	out.Upgrades = in.Upgrades
	in.AddressSettings.DeepCopyInto(&out.AddressSettings)
	if in.BrokerProperties != nil {
		in, out := &in.BrokerProperties, &out.BrokerProperties
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceTemplates != nil {
		in, out := &in.ResourceTemplates, &out.ResourceTemplates
		*out = make([]ResourceTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Restricted != nil {
		in, out := &in.Restricted, &out.Restricted
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerSpec.
func (in *BrokerSpec) DeepCopy() *BrokerSpec {
	if in == nil {
		return nil
	}
	out := new(BrokerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerStatus) DeepCopyInto(out *BrokerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.PodStatus.DeepCopyInto(&out.PodStatus)
	if in.ExternalConfigs != nil {
		in, out := &in.ExternalConfigs, &out.ExternalConfigs
		*out = make([]ExternalConfigStatus, len(*in))
		copy(*out, *in)
	}
	out.Version = in.Version
	out.Upgrade = in.Upgrade
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerStatus.
func (in *BrokerStatus) DeepCopy() *BrokerStatus {
	if in == nil {
		return nil
	}
	out := new(BrokerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerUpgrades) DeepCopyInto(out *BrokerUpgrades) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerUpgrades.
func (in *BrokerUpgrades) DeepCopy() *BrokerUpgrades {
	if in == nil {
		return nil
	}
	out := new(BrokerUpgrades)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorType) DeepCopyInto(out *ConnectorType) {
	*out = *in
	if in.ExposeMode != nil {
		in, out := &in.ExposeMode, &out.ExposeMode
		*out = new(ExposeMode)
		**out = **in
	}
	if in.TrustSecret != nil {
		in, out := &in.TrustSecret, &out.TrustSecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorType.
func (in *ConnectorType) DeepCopy() *ConnectorType {
	if in == nil {
		return nil
	}
	out := new(ConnectorType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleType) DeepCopyInto(out *ConsoleType) {
	*out = *in
	if in.ExposeMode != nil {
		in, out := &in.ExposeMode, &out.ExposeMode
		*out = new(ExposeMode)
		**out = **in
	}
	if in.TrustSecret != nil {
		in, out := &in.TrustSecret, &out.TrustSecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleType.
func (in *ConsoleType) DeepCopy() *ConsoleType {
	if in == nil {
		return nil
	}
	out := new(ConsoleType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentPlanType) DeepCopyInto(out *DeploymentPlanType) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int32)
		**out = **in
	}
	if in.MessageMigration != nil {
		in, out := &in.MessageMigration, &out.MessageMigration
		*out = new(bool)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.Storage = in.Storage
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ExtraMounts.DeepCopyInto(&out.ExtraMounts)
	if in.Clustered != nil {
		in, out := &in.Clustered, &out.Clustered
		*out = new(bool)
		**out = **in
	}
	in.PodSecurity.DeepCopyInto(&out.PodSecurity)
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableMetricsPlugin != nil {
		in, out := &in.EnableMetricsPlugin, &out.EnableMetricsPlugin
		*out = new(bool)
		**out = **in
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Affinity.DeepCopyInto(&out.Affinity)
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(policyv1.PodDisruptionBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.ContainerSecurityContext != nil {
		in, out := &in.ContainerSecurityContext, &out.ContainerSecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraVolumes != nil {
		in, out := &in.ExtraVolumes, &out.ExtraVolumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumeMounts != nil {
		in, out := &in.ExtraVolumeMounts, &out.ExtraVolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumeClaimTemplates != nil {
		in, out := &in.ExtraVolumeClaimTemplates, &out.ExtraVolumeClaimTemplates
		*out = make([]VolumeClaimTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentPlanType.
func (in *DeploymentPlanType) DeepCopy() *DeploymentPlanType {
	if in == nil {
		return nil
	}
	out := new(DeploymentPlanType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalConfigStatus) DeepCopyInto(out *ExternalConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalConfigStatus.
func (in *ExternalConfigStatus) DeepCopy() *ExternalConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtraMountsType) DeepCopyInto(out *ExtraMountsType) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtraMountsType.
func (in *ExtraMountsType) DeepCopy() *ExtraMountsType {
	if in == nil {
		return nil
	}
	out := new(ExtraMountsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectMeta) DeepCopyInto(out *ObjectMeta) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectMeta.
func (in *ObjectMeta) DeepCopy() *ObjectMeta {
	if in == nil {
		return nil
	}
	out := new(ObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSecurityType) DeepCopyInto(out *PodSecurityType) {
	*out = *in
	if in.ServiceAccountName != nil {
		in, out := &in.ServiceAccountName, &out.ServiceAccountName
		*out = new(string)
		**out = **in
	}
	if in.RunAsUser != nil {
		in, out := &in.RunAsUser, &out.RunAsUser
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSecurityType.
func (in *PodSecurityType) DeepCopy() *PodSecurityType {
	if in == nil {
		return nil
	}
	out := new(PodSecurityType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelector) DeepCopyInto(out *ResourceSelector) {
	*out = *in
	if in.APIGroup != nil {
		in, out := &in.APIGroup, &out.APIGroup
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelector.
func (in *ResourceSelector) DeepCopy() *ResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceTemplate) DeepCopyInto(out *ResourceTemplate) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(ResourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Patch != nil {
		in, out := &in.Patch, &out.Patch
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceTemplate.
func (in *ResourceTemplate) DeepCopy() *ResourceTemplate {
	if in == nil {
		return nil
	}
	out := new(ResourceTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageType) DeepCopyInto(out *StorageType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageType.
func (in *StorageType) DeepCopy() *StorageType {
	if in == nil {
		return nil
	}
	out := new(StorageType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeStatus) DeepCopyInto(out *UpgradeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeStatus.
func (in *UpgradeStatus) DeepCopy() *UpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionStatus) DeepCopyInto(out *VersionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionStatus.
func (in *VersionStatus) DeepCopy() *VersionStatus {
	if in == nil {
		return nil
	}
	out := new(VersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeClaimTemplate) DeepCopyInto(out *VolumeClaimTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeClaimTemplate.
func (in *VolumeClaimTemplate) DeepCopy() *VolumeClaimTemplate {
	if in == nil {
		return nil
	}
	out := new(VolumeClaimTemplate)
	in.DeepCopyInto(out)
	return out
}
