apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_BROKER_INIT_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-25715-20260413001626
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:e9ce94ad4b5455f1c8d577d6dac16d2b0b05034daa18550793e940553015612f
        - name: RELATED_IMAGE_BROKER_KUBERNETES_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-34416-20260413000126
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:1e582af36f8310f0a857441b1ef1378acb7b334258e5999929be4377a730cd02
        - name: RELATED_IMAGE_BROKER_INIT_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-25715-20260413001626
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:e9ce94ad4b5455f1c8d577d6dac16d2b0b05034daa18550793e940553015612f
        - name: RELATED_IMAGE_BROKER_KUBERNETES_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-34416-20260413000126
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:1e582af36f8310f0a857441b1ef1378acb7b334258e5999929be4377a730cd02
        - name: RELATED_IMAGE_BROKER_INIT_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-25715-20260413001626
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:e9ce94ad4b5455f1c8d577d6dac16d2b0b05034daa18550793e940553015612f
        - name: RELATED_IMAGE_BROKER_KUBERNETES_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-34416-20260413000126
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:1e582af36f8310f0a857441b1ef1378acb7b334258e5999929be4377a730cd02
