apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: controller-manager-netpol
  labels:
    control-plane: controller-manager
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
      name: arkmq-org-broker-operator
  policyTypes:
    - Ingress
  ingress:
    # Kubelet health and readiness probes
    - ports:
        - port: 8081
          protocol: TCP
    # Metrics endpoint
    - ports:
        - port: 8383
          protocol: TCP
