apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    control-plane: controller-manager
  name: arkmq-org-broker-controller-manager-netpol
spec:
  ingress:
  - ports:
    - port: 8081
      protocol: TCP
  - ports:
    - port: 8383
      protocol: TCP
  podSelector:
    matchLabels:
      control-plane: controller-manager
      name: arkmq-org-broker-operator
  policyTypes:
  - Ingress
