package templates

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

func mustRender(name string, cfg any) string {
	data, err := Render(name, cfg)
	ExpectWithOffset(1, err).NotTo(HaveOccurred())
	return string(data)
}

func mustRenderServicePrometheus(cfg ServicePrometheusConfig, appQueues map[string]bool) string {
	data, err := RenderServicePrometheus(cfg, appQueues)
	ExpectWithOffset(1, err).NotTo(HaveOccurred())
	return string(data)
}

var _ = Describe("SecurityConfigData", func() {
	It("includes the login.config URL pointing to the mount path", func() {
		data := mustRender(Security, SecurityConfig{MountPathRoot: "/amq/secrets/my-props"})
		Expect(data).To(ContainSubstring("login.config.url.1=file:/amq/secrets/my-props/login.config"))
	})

	It("includes both PEM security providers", func() {
		data := mustRender(Security, SecurityConfig{MountPathRoot: "/amq/secrets/my-props"})
		Expect(data).To(ContainSubstring("security.provider.13=de.dentrassi.crypto.pem.PemKeyStoreProvider"))
		Expect(data).To(ContainSubstring("fips.provider.8=de.dentrassi.crypto.pem.PemKeyStoreProvider"))
	})

	It("starts with a # comment header", func() {
		data := mustRender(Security, SecurityConfig{MountPathRoot: "/path"})
		Expect(data).To(HavePrefix("# generated by crd"))
	})
})

var _ = Describe("LoginConfigData", func() {
	It("opens with the realm name", func() {
		data := mustRender(Login, LoginConfig{Realm: "myRealm", MountPathRoot: "/amq/secrets/props", CertUsersKey: "users.properties", CertRolesKey: "roles.properties"})
		Expect(data).To(ContainSubstring("myRealm {"))
	})

	It("includes the TextFileCertificateLoginModule", func() {
		data := mustRender(Login, LoginConfig{Realm: "myRealm", MountPathRoot: "/amq/secrets/props", CertUsersKey: "users.properties", CertRolesKey: "roles.properties"})
		Expect(data).To(ContainSubstring("TextFileCertificateLoginModule required"))
	})

	It("sets the certUsersKey for textfiledn.user", func() {
		data := mustRender(Login, LoginConfig{Realm: "myRealm", MountPathRoot: "/path", CertUsersKey: "my-users.properties", CertRolesKey: "my-roles.properties"})
		Expect(data).To(ContainSubstring("org.apache.activemq.jaas.textfiledn.user=my-users.properties"))
	})

	It("sets the certRolesKey for textfiledn.role", func() {
		data := mustRender(Login, LoginConfig{Realm: "myRealm", MountPathRoot: "/path", CertUsersKey: "my-users.properties", CertRolesKey: "my-roles.properties"})
		Expect(data).To(ContainSubstring("org.apache.activemq.jaas.textfiledn.role=my-roles.properties"))
	})

	It("sets the baseDir to the mount path root", func() {
		data := mustRender(Login, LoginConfig{Realm: "myRealm", MountPathRoot: "/amq/secrets/props", CertUsersKey: "u", CertRolesKey: "r"})
		Expect(data).To(ContainSubstring(`baseDir="/amq/secrets/props"`))
	})

	It("uses // as the comment character", func() {
		data := mustRender(Login, LoginConfig{Realm: "myRealm", MountPathRoot: "/path", CertUsersKey: "u", CertRolesKey: "r"})
		Expect(data).To(HavePrefix("// generated by crd"))
	})
})

var _ = Describe("BrokerCertUsersData", func() {
	It("includes the hardcoded hawtio entry", func() {
		data := mustRender(CertUsers, CertUsersConfig{OperatorCN: "op-cn", OperandCN: "operand-cn"})
		Expect(data).To(ContainSubstring("hawtio=/CN = hawtio-online"))
	})

	It("includes the operator CN in a regex pattern", func() {
		data := mustRender(CertUsers, CertUsersConfig{OperatorCN: "my-operator", OperandCN: "my-operand"})
		Expect(data).To(ContainSubstring("operator=/.*my-operator.*/"))
	})

	It("includes the operand CN as the probe entry", func() {
		data := mustRender(CertUsers, CertUsersConfig{OperatorCN: "op", OperandCN: "my-operand"})
		Expect(data).To(ContainSubstring("probe=/.*my-operand.*/"))
	})

	It("includes the prometheus CN when non-empty", func() {
		data := mustRender(CertUsers, CertUsersConfig{OperatorCN: "op", OperandCN: "operand", PrometheusCN: "my-prometheus"})
		Expect(data).To(ContainSubstring("prometheus=/.*my-prometheus.*/"))
	})

	It("omits the prometheus entry when prometheusCN is empty", func() {
		data := mustRender(CertUsers, CertUsersConfig{OperatorCN: "op", OperandCN: "operand"})
		Expect(data).NotTo(ContainSubstring("prometheus="))
	})
})

var _ = Describe("BrokerCertRolesData", func() {
	It("assigns status to operator and probe", func() {
		data := string(RenderCertRoles())
		Expect(data).To(ContainSubstring("status=operator,probe"))
	})

	It("assigns metrics to operator and prometheus", func() {
		data := string(RenderCertRoles())
		Expect(data).To(ContainSubstring("metrics=operator,prometheus"))
	})

	It("assigns hawtio to hawtio", func() {
		data := string(RenderCertRoles())
		Expect(data).To(ContainSubstring("hawtio=hawtio"))
	})

	It("produces the same bytes on every call", func() {
		Expect(RenderCertRoles()).To(Equal(RenderCertRoles()))
	})
})

var _ = Describe("JolokiaConfigData", func() {
	It("sets protocol to https", func() {
		data := mustRender(Jolokia, JolokiaConfig{CACertPath: "/ca/path", ServerCertPath: "/cert/path", ServerKeyPath: "/key/path"})
		Expect(data).To(ContainSubstring("protocol=https"))
	})

	It("sets the caCert to the provided path", func() {
		data := mustRender(Jolokia, JolokiaConfig{CACertPath: "/ca/path/ca.crt", ServerCertPath: "/cert/path", ServerKeyPath: "/key/path"})
		Expect(data).To(ContainSubstring("caCert=/ca/path/ca.crt"))
	})

	It("sets serverCert to the provided path", func() {
		data := mustRender(Jolokia, JolokiaConfig{CACertPath: "/ca", ServerCertPath: "/secrets/broker/tls.crt", ServerKeyPath: "/key"})
		Expect(data).To(ContainSubstring("serverCert=/secrets/broker/tls.crt"))
	})

	It("sets serverKey to the provided path", func() {
		data := mustRender(Jolokia, JolokiaConfig{CACertPath: "/ca", ServerCertPath: "/cert", ServerKeyPath: "/secrets/broker/tls.key"})
		Expect(data).To(ContainSubstring("serverKey=/secrets/broker/tls.key"))
	})

	It("enables mutual TLS client authentication", func() {
		data := mustRender(Jolokia, JolokiaConfig{CACertPath: "/ca", ServerCertPath: "/cert", ServerKeyPath: "/key"})
		Expect(data).To(ContainSubstring("useSslClientAuthentication=true"))
	})

	It("binds to port 8778", func() {
		data := mustRender(Jolokia, JolokiaConfig{CACertPath: "/ca", ServerCertPath: "/cert", ServerKeyPath: "/key"})
		Expect(data).To(ContainSubstring("port=8778"))
	})
})

var _ = Describe("PemCfgData", func() {
	It("includes source.key at the provided path", func() {
		data := mustRender(PemCfg, PemCfgConfig{CertKeyPath: "/secrets/broker/tls.key", CertCrtPath: "/secrets/broker/tls.crt"})
		Expect(data).To(ContainSubstring("source.key=/secrets/broker/tls.key"))
	})

	It("includes source.cert at the provided path", func() {
		data := mustRender(PemCfg, PemCfgConfig{CertKeyPath: "/secrets/broker/tls.key", CertCrtPath: "/secrets/broker/tls.crt"})
		Expect(data).To(ContainSubstring("source.cert=/secrets/broker/tls.crt"))
	})

	It("includes the alias line when alias is non-empty", func() {
		data := mustRender(PemCfg, PemCfgConfig{Alias: "alias", CertKeyPath: "/key", CertCrtPath: "/cert"})
		Expect(data).To(ContainSubstring("alias=alias"))
	})

	It("omits the alias line when alias is empty", func() {
		data := mustRender(PemCfg, PemCfgConfig{CertKeyPath: "/key", CertCrtPath: "/cert"})
		Expect(data).NotTo(ContainSubstring("alias="))
	})
})

var _ = Describe("BrokerPrometheusConfigData", func() {
	It("includes the SSL keyStore pointing to the pemcfg path", func() {
		data := mustRender(BrokerPrometheus, BrokerPrometheusConfig{PemCfgPath: "/path/_cert.pemcfg", CATrustStorePath: "/ca/trust", BrokerName: "my-broker"})
		Expect(data).To(ContainSubstring("filename: /path/_cert.pemcfg"))
		Expect(data).To(ContainSubstring("type: PEMCFG"))
	})

	It("includes the trustStore pointing to the CA path", func() {
		data := mustRender(BrokerPrometheus, BrokerPrometheusConfig{PemCfgPath: "/pem", CATrustStorePath: "/amq/secrets/ca/ca.crt", BrokerName: "my-broker"})
		Expect(data).To(ContainSubstring("filename: /amq/secrets/ca/ca.crt"))
		Expect(data).To(ContainSubstring("type: PEMCA"))
	})

	It("includes the broker name in includeObjectNames", func() {
		data := mustRender(BrokerPrometheus, BrokerPrometheusConfig{PemCfgPath: "/pem", CATrustStorePath: "/ca", BrokerName: "my-broker"})
		Expect(data).To(ContainSubstring(`broker="my-broker"`))
	})

	It("includes rules for TotalMessageCount, TotalMessagesAdded, and TotalMessagesAcknowledged", func() {
		data := mustRender(BrokerPrometheus, BrokerPrometheusConfig{PemCfgPath: "/pem", CATrustStorePath: "/ca", BrokerName: "my-broker"})
		Expect(data).To(ContainSubstring("artemis_total_pending_message_count"))
		Expect(data).To(ContainSubstring("artemis_total_consumed_message_count"))
		Expect(data).To(ContainSubstring("artemis_total_produced_message_count"))
	})

	It("enables lowercase output names", func() {
		data := mustRender(BrokerPrometheus, BrokerPrometheusConfig{PemCfgPath: "/pem", CATrustStorePath: "/ca", BrokerName: "my-broker"})
		Expect(data).To(ContainSubstring("lowercaseOutputName: true"))
		Expect(data).To(ContainSubstring("lowercaseOutputLabelNames: true"))
	})
})

var _ = Describe("ServicePrometheusConfigData", func() {
	It("includes the SSL keyStore and trustStore", func() {
		data := mustRenderServicePrometheus(ServicePrometheusConfig{PemCfgPath: "/path/_cert.pemcfg", CATrustStorePath: "/ca/trust", BrokerName: "svc"}, nil)
		Expect(data).To(ContainSubstring("filename: /path/_cert.pemcfg"))
		Expect(data).To(ContainSubstring("filename: /ca/trust"))
	})

	It("uses attrNameSnakeCase instead of lowercaseOutputName", func() {
		data := mustRenderServicePrometheus(ServicePrometheusConfig{PemCfgPath: "/pem", CATrustStorePath: "/ca", BrokerName: "svc"}, nil)
		Expect(data).To(ContainSubstring("attrNameSnakeCase: true"))
		Expect(data).NotTo(ContainSubstring("lowercaseOutputName"))
	})

	It("includes queue-level includeObjectNameAttributes when appQueues is non-empty", func() {
		queues := map[string]bool{"MY.QUEUE": true}
		data := mustRenderServicePrometheus(ServicePrometheusConfig{PemCfgPath: "/pem", CATrustStorePath: "/ca", BrokerName: "svc"}, queues)
		Expect(data).To(ContainSubstring("includeObjectNameAttributes:"))
		Expect(data).To(ContainSubstring("MY.QUEUE"))
	})

	It("omits includeObjectNameAttributes when appQueues is empty", func() {
		data := mustRenderServicePrometheus(ServicePrometheusConfig{PemCfgPath: "/pem", CATrustStorePath: "/ca", BrokerName: "svc"}, nil)
		Expect(data).NotTo(ContainSubstring("includeObjectNameAttributes:"))
	})

	It("routes multicast addresses (with ::) to multicast routing-type", func() {
		queues := map[string]bool{"MY.TOPIC::MY.SUBSCRIPTION": true}
		data := mustRenderServicePrometheus(ServicePrometheusConfig{PemCfgPath: "/pem", CATrustStorePath: "/ca", BrokerName: "svc"}, queues)
		Expect(data).To(ContainSubstring(`routing-type="multicast"`))
		Expect(data).To(ContainSubstring(`address="MY.TOPIC"`))
		Expect(data).To(ContainSubstring(`queue="MY.SUBSCRIPTION"`))
	})

	It("routes plain addresses (no ::) to anycast routing-type", func() {
		queues := map[string]bool{"MY.QUEUE": true}
		data := mustRenderServicePrometheus(ServicePrometheusConfig{PemCfgPath: "/pem", CATrustStorePath: "/ca", BrokerName: "svc"}, queues)
		Expect(data).To(ContainSubstring(`routing-type="anycast"`))
		Expect(data).To(ContainSubstring(`address="MY.QUEUE"`))
	})

	It("produces queue attributes in deterministic order", func() {
		queues := map[string]bool{"B.QUEUE": true, "A.QUEUE": true}
		first := mustRenderServicePrometheus(ServicePrometheusConfig{PemCfgPath: "/pem", CATrustStorePath: "/ca", BrokerName: "svc"}, queues)
		second := mustRenderServicePrometheus(ServicePrometheusConfig{PemCfgPath: "/pem", CATrustStorePath: "/ca", BrokerName: "svc"}, queues)
		Expect(first).To(Equal(second))
		Expect(first).To(ContainSubstring("A.QUEUE"))
		aIdx := indexOfString(first, "A.QUEUE")
		bIdx := indexOfString(first, "B.QUEUE")
		Expect(aIdx).To(BeNumerically("<", bIdx))
	})

	It("includes the broker_queue rules pattern", func() {
		data := mustRenderServicePrometheus(ServicePrometheusConfig{PemCfgPath: "/pem", CATrustStorePath: "/ca", BrokerName: "svc"}, nil)
		Expect(data).To(ContainSubstring("broker_queue_$5"))
	})
})

func indexOfString(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
