schema: olm.template.basic
entries:
  - schema: olm.package
    name: arkmq-org-broker-operator
    defaultChannel: stable
  - schema: olm.channel
    package: arkmq-org-broker-operator
    name: stable
    entries: []
