schema: olm.template.basic
entries:
  - schema: olm.package
    name: activemq-artemis-operator
    defaultChannel: stable
  - schema: olm.channel
    package: activemq-artemis-operator
    name: stable
    entries: []
