apiVersion: broker.arkmq.org/v1beta2
kind: Broker
metadata:
  name: my-broker
spec:
  acceptors:
  - name: ssl
    port: 61618
    protocols: all
    sslEnabled: true
    sslSecret: ssl-acceptor-ssl-secret
  deploymentPlan:
    extraMounts:
      secrets:
      - amq-ssl-secret
      configMaps:
      - ca-bundle