apiVersion: broker.arkmq.org/v1beta2
kind: Broker
metadata:
  name: my-broker-resources
spec:
  deploymentPlan:
    resources:
      limits:
        cpu: "500m"
        memory: "1024Mi"
      requests:
        cpu: "250m"
        memory: "512Mi"
