apiVersion: broker.arkmq.org/v1beta2
kind: Broker
metadata:
  name: my-broker
spec:
  deploymentPlan:
    size: 2
    persistenceEnabled: true
    # messageMigration requires 2+ brokers
    messageMigration: true
