apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: amq-broker-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        com.company: Red_Hat
        control-plane: controller-manager
        name: amq-broker-operator
        rht.comp: Broker_AMQ
        rht.comp_ver: 8.0.0
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: 2026.Q2
        rht.subcomp: broker-amq-operator
        rht.subcomp_t: application
    spec:
      containers:
      - args:
        - --zap-log-level=info
        - --zap-encoder=console
        - --zap-time-encoding=iso8601
        - --leader-elect
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: RELATED_IMAGE_BROKER_INIT_800
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:d95ba4d8ebf4989d673f9cf2fed1042c51d23847ed73dcc96664472cff0f16b3
        - name: RELATED_IMAGE_BROKER_KUBERNETES_800
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:6540397631288fdfd6fceb8f058816cb49a6677fd85f25b23e57ad40767e6af6
        - name: RELATED_IMAGE_BROKER_INIT_800_ppc64le
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:d95ba4d8ebf4989d673f9cf2fed1042c51d23847ed73dcc96664472cff0f16b3
        - name: RELATED_IMAGE_BROKER_KUBERNETES_800_ppc64le
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:6540397631288fdfd6fceb8f058816cb49a6677fd85f25b23e57ad40767e6af6
        - name: RELATED_IMAGE_BROKER_INIT_800_s390x
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:d95ba4d8ebf4989d673f9cf2fed1042c51d23847ed73dcc96664472cff0f16b3
        - name: RELATED_IMAGE_BROKER_KUBERNETES_800_s390x
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:6540397631288fdfd6fceb8f058816cb49a6677fd85f25b23e57ad40767e6af6
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_WEBHOOKS
          value: "false"
        image: registry.redhat.io/amq8/amq-broker-rhel9-operator@sha256:d31240104ab99823b287a699dfb9747937b6f5f87ce51bdc835f82e9b6853ce5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8383
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 384Mi
          requests:
            cpu: 200m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePolicy: FallbackToLogsOnError
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: amq-broker-controller-manager
      terminationGracePeriodSeconds: 10
