apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: activemq-artemis-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - pods
  - routes
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemisaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemisaddresses/finalizers
  verbs:
  - update
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemisaddresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemises/finalizers
  verbs:
  - update
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemises/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemisscaledowns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemisscaledowns/finalizers
  verbs:
  - update
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemisscaledowns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemissecurities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemissecurities/finalizers
  verbs:
  - update
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemissecurities/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - broker.amq.io
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  - routes/status
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
