apiVersion: broker.arkmq.org/v1beta2
kind: BrokerApp
metadata:
  name: wq-app
spec:
  capabilities:
    - producerOf:
        - address: APP.JOBS
  selector:
    matchLabels:
      forWorkQueue: 'true'
status:
  conditions: []