apiVersion: arkmq.org/v1beta2
kind: BrokerApp
metadata:
  name: wq-app
spec:
  acceptor:
    port: 61616
  capabilities: [
    producerOf: [
      address: APP.JOBS
    ]
  ]
  selector:
    matchLabels:
      forWorkQueue: 'true'
status:
  conditions: []