FROM registry.access.redhat.com/ubi9/openjdk-25 AS builder

USER root
WORKDIR /build

RUN microdnf install -y maven --setopt=install_weak_deps=0 && microdnf clean all

COPY pom.xml pom.xml

RUN mvn dependency:resolve-plugins dependency:resolve -q

COPY src/ src/
RUN mvn package -DskipTests -q

FROM registry.access.redhat.com/ubi9/openjdk-25-runtime

ENV LANGUAGE='en_US:en'

COPY --chown=185 --from=builder /build/target/quarkus-app/lib/       /deployments/lib/
COPY --chown=185 --from=builder /build/target/quarkus-app/*.jar       /deployments/
COPY --chown=185 --from=builder /build/target/quarkus-app/app/        /deployments/app/
COPY --chown=185 --from=builder /build/target/quarkus-app/quarkus/    /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
