// Package brokerproperties provides shared broker properties utilities for Broker and BrokerCluster.
package brokerproperties

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"hash/adler32"
	"regexp"
	"sort"
	"strings"
	"unicode"

	v1beta2 "github.com/arkmq-org/arkmq-org-broker-operator/v2/api/v1beta2"
	"github.com/arkmq-org/arkmq-org-broker-operator/v2/pkg/utils/certutil"
	"github.com/arkmq-org/arkmq-org-broker-operator/v2/pkg/utils/common"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	OrdinalPrefix        = "broker-"
	OrdinalPrefixSep     = "."
	UncheckedPrefix      = "_"
	PropertiesSuffix     = ".properties"
	BrokerPropertiesName = "broker" + PropertiesSuffix
	JaasConfigKey        = "login.config"
	LoggingConfigKey     = "logging" + PropertiesSuffix
	JaasConfigSuffix     = "-jaas-config"
	LoggingConfigSuffix  = "-logging-config"
)

func NewPropsWithHeader() *bytes.Buffer {
	return newBufferWithHeader("#")
}

func NewBufferWithHeader(commentChars string) *bytes.Buffer {
	return newBufferWithHeader(commentChars)
}

func newBufferWithHeader(commentChars string) *bytes.Buffer {
	buf := &bytes.Buffer{}
	fmt.Fprintf(buf, "%s generated by crd\n", commentChars)
	fmt.Fprintf(buf, "%s\n", commentChars)
	return buf
}

func BrokerPropertiesData(props []string) map[string][]byte {
	contents := make(map[string][]byte)

	buf := &bytes.Buffer{}
	fmt.Fprintln(buf, "# generated by crd")
	fmt.Fprintln(buf, "#")

	for _, propertyKeyVal := range props {
		matches := ParseBrokerPropertyWithOrdinal(propertyKeyVal)
		if len(matches) > 0 {
			mapKey := matches[1] + OrdinalPrefixSep + BrokerPropertiesName
			value := matches[2]
			existing, found := contents[mapKey]
			if found {
				contents[mapKey] = []byte(fmt.Sprintf("%s%s\n", existing, value))
			} else {
				contents[mapKey] = []byte(fmt.Sprintf("%s\n", value))
			}
		} else {
			fmt.Fprintf(buf, "%s\n", propertyKeyVal)
		}
	}

	contents[BrokerPropertiesName] = buf.Bytes()
	return contents
}

var brokerPropertyWithOrdinalRegex *regexp.Regexp

func ParseBrokerPropertyWithOrdinal(property string) []string {
	if brokerPropertyWithOrdinalRegex == nil {
		brokerPropertyWithOrdinalRegex = regexp.MustCompile("^(" + regexp.QuoteMeta(OrdinalPrefix) + "[0-9]+)" + regexp.QuoteMeta(OrdinalPrefixSep) + "(.*)$")
	}
	return brokerPropertyWithOrdinalRegex.FindStringSubmatch(property)
}

func HasOrdinalPropertiesInData(brokerPropsData map[string][]byte) bool {
	for key := range brokerPropsData {
		if len(ParseBrokerPropertyWithOrdinal(key)) > 0 {
			return true
		}
	}
	return false
}

func Alder32Of(props []string) []byte {
	digest := adler32.New()
	for _, k := range props {
		digest.Write([]byte(k))
	}
	return digest.Sum(nil)
}

func Alder32StringValue(alder32Bytes []byte) string {
	return fmt.Sprintf("%d", binary.BigEndian.Uint32(alder32Bytes))
}

func Alder32FromData(data []byte) string {
	return Alder32StringValue(Alder32Of(ReadReplaceEscapes(KeyValuePairs(data))))
}

func SortedKeys(props map[string]string) []string {
	keys := make([]string, 0, len(props))
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func SortedKeysByteValue(props map[string][]byte) []string {
	keys := make([]string, 0, len(props))
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func KeyValuePairs(data []byte) []string {
	keyValuePairs := []string{}
	for _, lineToTrim := range strings.Split(string(data), "\n") {
		line := strings.TrimLeftFunc(lineToTrim, unicode.IsSpace)
		if strings.HasPrefix(line, "#") || strings.HasPrefix(line, "!") {
			continue
		}
		keyAndValue := strings.TrimSpace(line)
		if keyAndValue != "" {
			keyValuePairs = append(keyValuePairs, keyAndValue)
		}
	}
	return keyValuePairs
}

func ReadReplaceEscapes(values []string) []string {
	result := []string{}
	for _, keyAndValue := range values {
		equalsSeparator := "="
		tokens := strings.SplitN(keyAndValue, equalsSeparator, 2)
		if len(tokens) == 2 {
			keyAndValue = strings.TrimRightFunc(tokens[0], unicode.IsSpace) +
				equalsSeparator +
				strings.TrimLeftFunc(tokens[1], unicode.IsSpace)
		}
		keyAndValue = strings.ReplaceAll(keyAndValue, `\ `, ` `)
		keyAndValue = strings.ReplaceAll(keyAndValue, `\:`, `:`)
		keyAndValue = strings.ReplaceAll(keyAndValue, `\=`, `=`)
		keyAndValue = strings.ReplaceAll(keyAndValue, `\"`, `"`)
		result = append(result, keyAndValue)
	}
	return result
}

func DuplicateKeyIn(keyValues []string) string {
	seen := map[string]struct{}{}
	for _, kv := range keyValues {
		key := extractPropertyKey(kv)
		if _, found := seen[key]; found {
			return key
		}
		seen[key] = struct{}{}
	}
	return ""
}

func DuplicateKeyInContent(keyValues []byte) string {
	return DuplicateKeyIn(KeyValuePairs(keyValues))
}

func extractPropertyKey(keyAndValue string) string {
	for index, c := range keyAndValue {
		if c == '=' && index > 0 && keyAndValue[index-1] != '\\' {
			return keyAndValue[0:index]
		}
	}
	return keyAndValue
}

func GetConfigExtraMount(extraMounts v1beta2.ExtraMountsType, suffix string) (string, string, bool) {
	for _, cm := range extraMounts.ConfigMaps {
		if strings.HasSuffix(cm, suffix) {
			return "configmaps", cm, true
		}
	}
	for _, s := range extraMounts.Secrets {
		if strings.HasSuffix(s, suffix) {
			return "secrets", s, true
		}
	}
	return "", "", false
}

func GetJaasConfigExtraMountPath(extraMounts v1beta2.ExtraMountsType) (string, bool) {
	if t, name, found := GetConfigExtraMount(extraMounts, JaasConfigSuffix); found {
		return fmt.Sprintf("/amq/extra/%v/%v/login.config", t, name), true
	}
	return "", false
}

func GetLoggingConfigExtraMountPath(extraMounts v1beta2.ExtraMountsType) (string, bool) {
	if t, name, found := GetConfigExtraMount(extraMounts, LoggingConfigSuffix); found {
		return fmt.Sprintf("/amq/extra/%v/%v/logging.properties", t, name), true
	}
	return "", false
}

func HasExtraMounts(extraMounts v1beta2.ExtraMountsType) bool {
	return len(extraMounts.ConfigMaps) > 0 || len(extraMounts.Secrets) > 0
}

var loginConfigSyntaxMatcher *regexp.Regexp

func AssertSyntaxOkOnLoginConfigData(content []byte, name string, contextMessage string) *metav1.Condition {
	syntaxMatchRegEx := common.GetJaasConfigSyntaxMatchRegEx()
	if syntaxMatchRegEx != "" {
		if loginConfigSyntaxMatcher == nil {
			loginConfigSyntaxMatcher, _ = regexp.Compile(syntaxMatchRegEx)
		}
		if !loginConfigSyntaxMatcher.Match(content) {
			return &metav1.Condition{
				Type:    v1beta2.ValidConditionType,
				Status:  metav1.ConditionFalse,
				Reason:  v1beta2.ValidConditionFailedExtraMountReason,
				Message: fmt.Sprintf("%s content of login.config key in secret %v does not match supported jaas config file syntax", contextMessage, name),
			}
		}
	}
	return nil
}

func AssertInstanceCounts(instanceCounts map[string]int, contextMessage string) *metav1.Condition {
	for key, v := range instanceCounts {
		if v > 1 {
			return &metav1.Condition{
				Type:    v1beta2.ValidConditionType,
				Status:  metav1.ConditionFalse,
				Reason:  v1beta2.ValidConditionFailedExtraMountReason,
				Message: fmt.Sprintf("%s entry with suffix %v can only be supplied once", contextMessage, key),
			}
		}
	}
	return nil
}

func AssertConfigMapContainsKey(configMap corev1.ConfigMap, key string, contextMessage string) *metav1.Condition {
	if _, present := configMap.Data[key]; !present {
		return &metav1.Condition{
			Type:    v1beta2.ValidConditionType,
			Status:  metav1.ConditionFalse,
			Reason:  v1beta2.ValidConditionFailedExtraMountReason,
			Message: fmt.Sprintf("%s configmap %v must have key %v", contextMessage, configMap.Name, key),
		}
	}
	return nil
}

func AssertNoDupKeyInProperties(secret corev1.Secret, contextMessage string) *metav1.Condition {
	for key, data := range secret.Data {
		if !strings.HasPrefix(key, UncheckedPrefix) && strings.HasSuffix(key, PropertiesSuffix) {
			if duplicateKey := DuplicateKeyInContent(data); duplicateKey != "" {
				return &metav1.Condition{
					Type:    v1beta2.ValidConditionType,
					Status:  metav1.ConditionFalse,
					Reason:  v1beta2.ValidConditionFailedExtraMountReason,
					Message: fmt.Sprintf("%s properties secret %v entry %v has a duplicate key for %v", contextMessage, secret.Name, key, duplicateKey),
				}
			}
		}
	}
	return nil
}

func AssertSecretContainsKey(secret corev1.Secret, key string, contextMessage string) *metav1.Condition {
	isCertSecret, isValid := certutil.IsSecretFromCert(&secret)
	if isCertSecret {
		if isValid {
			return nil
		}
		return &metav1.Condition{
			Type:    v1beta2.ValidConditionType,
			Status:  metav1.ConditionFalse,
			Reason:  v1beta2.ValidConditionInvalidCertSecretReason,
			Message: fmt.Sprintf("%s certificate secret %s not valid, must have keys ca.crt tls.crt tls.key", contextMessage, secret.Name),
		}
	}
	if _, present := secret.Data[key]; !present {
		return &metav1.Condition{
			Type:    v1beta2.ValidConditionType,
			Status:  metav1.ConditionFalse,
			Reason:  v1beta2.ValidConditionFailedExtraMountReason,
			Message: fmt.Sprintf("%s secret %v must have key %v", contextMessage, secret.Name, key),
		}
	}
	return nil
}

func AssertSecretContainsOneOf(secret corev1.Secret, keys []string, contextMessage string) *metav1.Condition {
	ok, valid := certutil.IsSecretFromCert(&secret)
	if ok {
		if valid {
			return nil
		}
		return &metav1.Condition{
			Type:    v1beta2.ValidConditionType,
			Status:  metav1.ConditionFalse,
			Reason:  v1beta2.ValidConditionInvalidCertSecretReason,
			Message: fmt.Sprintf("%s secret %s must contain keys %v", contextMessage, secret.Name, "ca.crt,tls.crt,tls.key"),
		}
	}
	for _, key := range keys {
		if _, present := secret.Data[key]; present {
			return nil
		}
	}
	return &metav1.Condition{
		Type:    v1beta2.ValidConditionType,
		Status:  metav1.ConditionFalse,
		Reason:  v1beta2.ValidConditionFailedExtraMountReason,
		Message: fmt.Sprintf("%s secret %v must contain one of following keys %v", contextMessage, secret.Name, keys),
	}
}
