package brokerproperties

import (
	"strings"

	v1beta2 "github.com/arkmq-org/arkmq-org-broker-operator/v2/api/v1beta2"
	"github.com/arkmq-org/arkmq-org-broker-operator/v2/pkg/utils/certutil"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ = Describe("NewPropsWithHeader", func() {
	It("begins with a # comment line containing 'generated by crd'", func() {
		buf := NewPropsWithHeader()
		Expect(buf.String()).To(HavePrefix("# generated by crd"))
	})

	It("produces a non-empty buffer", func() {
		buf := NewPropsWithHeader()
		Expect(buf.Len()).To(BeNumerically(">", 0))
	})
})

var _ = Describe("NewBufferWithHeader", func() {
	It("uses the supplied comment character for each header line", func() {
		buf := NewBufferWithHeader("//")
		lines := strings.Split(buf.String(), "\n")
		Expect(lines[0]).To(HavePrefix("//"))
	})

	It("first line contains 'generated by crd'", func() {
		buf := NewBufferWithHeader("//")
		Expect(buf.String()).To(ContainSubstring("generated by crd"))
	})

	It("uses # when called with #", func() {
		buf := NewBufferWithHeader("#")
		Expect(buf.String()).To(HavePrefix("# generated by crd"))
	})
})

var _ = Describe("BrokerPropertiesData", func() {
	It("returns a map containing the broker.properties key for regular props", func() {
		data := BrokerPropertiesData([]string{"foo=bar", "baz=qux"})
		Expect(data).To(HaveKey(BrokerPropertiesName))
	})

	It("places regular properties into broker.properties content", func() {
		data := BrokerPropertiesData([]string{"foo=bar"})
		content := string(data[BrokerPropertiesName])
		Expect(content).To(ContainSubstring("foo=bar"))
	})

	It("routes an ordinal-prefixed property into its own per-ordinal file", func() {
		data := BrokerPropertiesData([]string{"broker-0.foo=bar"})
		Expect(data).To(HaveKey("broker-0" + OrdinalPrefixSep + BrokerPropertiesName))
		Expect(data).NotTo(HaveKey("broker-1" + OrdinalPrefixSep + BrokerPropertiesName))
	})

	It("the per-ordinal file contains only the value portion, not the ordinal prefix", func() {
		data := BrokerPropertiesData([]string{"broker-0.foo=bar"})
		content := string(data["broker-0"+OrdinalPrefixSep+BrokerPropertiesName])
		Expect(content).To(ContainSubstring("foo=bar"))
		Expect(content).NotTo(ContainSubstring("broker-0"))
	})

	It("accumulates multiple properties for the same ordinal in one file", func() {
		data := BrokerPropertiesData([]string{"broker-0.foo=bar", "broker-0.baz=qux"})
		content := string(data["broker-0"+OrdinalPrefixSep+BrokerPropertiesName])
		Expect(content).To(ContainSubstring("foo=bar"))
		Expect(content).To(ContainSubstring("baz=qux"))
	})

	It("creates separate files for distinct ordinals", func() {
		data := BrokerPropertiesData([]string{"broker-0.foo=bar", "broker-1.baz=qux"})
		Expect(data).To(HaveKey("broker-0" + OrdinalPrefixSep + BrokerPropertiesName))
		Expect(data).To(HaveKey("broker-1" + OrdinalPrefixSep + BrokerPropertiesName))
	})

	It("keeps regular props out of per-ordinal files and vice versa", func() {
		data := BrokerPropertiesData([]string{"shared=yes", "broker-0.ordinal=only"})
		sharedContent := string(data[BrokerPropertiesName])
		ordinalContent := string(data["broker-0"+OrdinalPrefixSep+BrokerPropertiesName])
		Expect(sharedContent).To(ContainSubstring("shared=yes"))
		Expect(sharedContent).NotTo(ContainSubstring("ordinal=only"))
		Expect(ordinalContent).To(ContainSubstring("ordinal=only"))
		Expect(ordinalContent).NotTo(ContainSubstring("shared=yes"))
	})

	It("returns only broker.properties when the list is empty", func() {
		data := BrokerPropertiesData([]string{})
		Expect(data).To(HaveLen(1))
		Expect(data).To(HaveKey(BrokerPropertiesName))
	})
})

var _ = Describe("ParseBrokerPropertyWithOrdinal", func() {
	It("returns non-nil matches for a broker-N prefixed property", func() {
		matches := ParseBrokerPropertyWithOrdinal("broker-0.foo=bar")
		Expect(matches).NotTo(BeNil())
		Expect(len(matches)).To(BeNumerically(">=", 3))
	})

	It("captures the ordinal identifier in group 1", func() {
		matches := ParseBrokerPropertyWithOrdinal("broker-0.foo=bar")
		Expect(matches[1]).To(Equal("broker-0"))
	})

	It("captures the rest of the property (key=value) in group 2", func() {
		matches := ParseBrokerPropertyWithOrdinal("broker-0.foo=bar")
		Expect(matches[2]).To(Equal("foo=bar"))
	})

	It("matches multi-digit ordinals and captures key=value in group 2", func() {
		matches := ParseBrokerPropertyWithOrdinal("broker-999.maxDiskUsage=97")
		Expect(matches[0]).To(Equal("broker-999.maxDiskUsage=97"))
		Expect(matches[1]).To(Equal("broker-999"))
		Expect(matches[2]).To(Equal("maxDiskUsage=97"))
	})

	It("returns nil for a property with no ordinal prefix", func() {
		Expect(ParseBrokerPropertyWithOrdinal("foo=bar")).To(BeNil())
	})

	It("returns nil for broker- without digits", func() {
		Expect(ParseBrokerPropertyWithOrdinal("broker-.foo=bar")).To(BeNil())
	})

	It("returns nil for a property that only starts with broker-N without the separator", func() {
		Expect(ParseBrokerPropertyWithOrdinal("broker-0foo=bar")).To(BeNil())
	})

	It("returns nil when the ordinal prefix appears after another prefix", func() {
		Expect(ParseBrokerPropertyWithOrdinal("a.broker-0.maxDiskUsage")).To(BeNil())
	})
})

var _ = Describe("HasOrdinalPropertiesInData", func() {
	It("returns true when the map has a broker-N prefixed key", func() {
		data := map[string][]byte{
			"broker-0" + OrdinalPrefixSep + BrokerPropertiesName: []byte("foo=bar"),
		}
		Expect(HasOrdinalPropertiesInData(data)).To(BeTrue())
	})

	It("returns false when the map has only broker.properties", func() {
		data := map[string][]byte{
			BrokerPropertiesName: []byte("foo=bar"),
		}
		Expect(HasOrdinalPropertiesInData(data)).To(BeFalse())
	})

	It("returns false for an empty map", func() {
		Expect(HasOrdinalPropertiesInData(map[string][]byte{})).To(BeFalse())
	})
})

var _ = Describe("Alder32Of", func() {
	It("returns a non-nil, non-empty byte slice", func() {
		result := Alder32Of([]string{"foo=bar"})
		Expect(result).NotTo(BeNil())
		Expect(result).NotTo(BeEmpty())
	})

	It("returns the same bytes for the same input", func() {
		props := []string{"a=1", "b=2"}
		Expect(Alder32Of(props)).To(Equal(Alder32Of(props)))
	})

	It("returns different bytes for different inputs", func() {
		Expect(Alder32Of([]string{"a=1"})).NotTo(Equal(Alder32Of([]string{"b=2"})))
	})

	It("returns different bytes for different orderings", func() {
		Expect(Alder32Of([]string{"a=1", "b=2"})).NotTo(Equal(Alder32Of([]string{"b=2", "a=1"})))
	})
})

var _ = Describe("Alder32StringValue", func() {
	It("returns a non-empty decimal string", func() {
		bytes := Alder32Of([]string{"foo=bar"})
		s := Alder32StringValue(bytes)
		Expect(s).NotTo(BeEmpty())
		Expect(s).To(MatchRegexp(`^\d+$`))
	})

	It("returns the same string for the same byte input", func() {
		b := Alder32Of([]string{"consistent"})
		Expect(Alder32StringValue(b)).To(Equal(Alder32StringValue(b)))
	})
})

var _ = Describe("Alder32FromData", func() {
	It("returns the same value as computing from parsed key-value pairs", func() {
		raw := []byte("# comment\nfoo=bar\nbaz=qux\n")
		fromData := Alder32FromData(raw)
		fromPairs := Alder32StringValue(Alder32Of(ReadReplaceEscapes(KeyValuePairs(raw))))
		Expect(fromData).To(Equal(fromPairs))
	})

	It("ignores comments when computing the checksum", func() {
		withComment := []byte("# generated by crd\nfoo=bar\n")
		withoutComment := []byte("foo=bar\n")
		Expect(Alder32FromData(withComment)).To(Equal(Alder32FromData(withoutComment)))
	})

	It("produces the correct checksum for simple key=value pairs", func() {
		userProps := "admin=admin\n\t\t\ttom=tom\n\t\t\tpeter=peter"
		Expect(Alder32FromData([]byte(userProps))).To(ContainSubstring("2905476010"))
	})

	It("produces the same checksum with or without empty lines", func() {
		withEmpty := "\n\t\t\t\tadmin=admin\n\t\t\t\ttom=tom\n\t\t\t\tpeter=peter"
		withoutEmpty := "admin=admin\n\t\t\t\ttom=tom\n\t\t\t\tpeter=peter"
		Expect(Alder32FromData([]byte(withEmpty))).To(Equal(Alder32FromData([]byte(withoutEmpty))))
	})

	It("trims whitespace around = when computing the checksum", func() {
		Expect(Alder32FromData([]byte("admin = joe"))).To(ContainSubstring("295568261"))
	})

	It("produces the correct checksum for properties with escaped spaces in keys", func() {
		userProps := "addressesSettings.#.redeliveryMultiplier=2.3\n\taddressesSettings.#.redeliveryCollisionAvoidanceFactor=1.2\n\taddressesSettings.Some\\ value\\ with\\ space.redeliveryCollisionAvoidanceFactor=1.2"
		Expect(Alder32FromData([]byte(userProps))).To(Equal("2211202255"))
	})

	It("produces the correct checksum for properties with escaped quotes and dots", func() {
		userProps := "addressSettings.#.redeliveryMultiplier=5\n    addressSettings.\\\"news.#\\\".redeliveryMultiplier=2\n    addressSettings.\\\"order.#\\\".redeliveryMultiplier=3"
		Expect(Alder32FromData([]byte(userProps))).To(Equal("3264295767"))
	})

	It("strips the generated-by-crd header comment before computing the checksum", func() {
		propsString := "# generated by crd\n#\nconnectionRouters.autoShard.keyType=CLIENT_ID\nconnectionRouters.autoShard.localTargetFilter=NULL|${STATEFUL_SET_ORDINAL}|-${STATEFUL_SET_ORDINAL}\nconnectionRouters.autoShard.policyConfiguration=CONSISTENT_HASH_MODULO\nconnectionRouters.autoShard.policyConfiguration.properties.MODULO=2\nacceptorConfigurations.tcp.params.router=autoShard\naddressesSettings.\"LB.#\".defaultAddressRoutingType=ANYCAST\n"
		Expect(Alder32FromData([]byte(propsString))).To(ContainSubstring("1897435425"))
	})

	It("produces the same checksum regardless of leading whitespace before comments", func() {
		withComments := "\n\t# rbac\n    control-plane=control-plane,control-plane-0,control-plane-1\n    consumers=c1,c2,c3,c4\n    producers=p\n\t! exclamation mark comment to strip with leading ws\n! as start of line to strip\n     # partitioned consumer roles for connectionRouter\nshard-consumers-broker-0=c1,c2\nshard-consumers-broker-1=c3,c4\n\n     \t\t# should resolve to NULL in absence of this\nshard-control-plane=control-plane,control-plane-0,control-plane-1\nshard-producers=p"
		withoutComments := "\ncontrol-plane=control-plane,control-plane-0,control-plane-1\nconsumers=c1,c2,c3,c4\nproducers=p\nshard-consumers-broker-0=c1,c2\nshard-consumers-broker-1=c3,c4\nshard-control-plane=control-plane,control-plane-0,control-plane-1\nshard-producers=p"
		Expect(Alder32FromData([]byte(withComments))).To(Equal(Alder32FromData([]byte(withoutComments))))
	})

	It("treats form feed as whitespace and strips it along with comments", func() {
		withFF := "\n\t\f# with form feed\nproducers=p"
		withoutFF := "producers=p"
		Expect(Alder32FromData([]byte(withFF))).To(Equal(Alder32FromData([]byte(withoutFF))))
	})
})

var _ = Describe("SortedKeys", func() {
	It("returns keys in alphabetical order", func() {
		props := map[string]string{"c": "3", "a": "1", "b": "2"}
		Expect(SortedKeys(props)).To(Equal([]string{"a", "b", "c"}))
	})

	It("returns an empty slice for an empty map", func() {
		Expect(SortedKeys(map[string]string{})).To(BeEmpty())
	})
})

var _ = Describe("SortedKeysByteValue", func() {
	It("returns keys in alphabetical order", func() {
		props := map[string][]byte{"z": {}, "a": {}, "m": {}}
		Expect(SortedKeysByteValue(props)).To(Equal([]string{"a", "m", "z"}))
	})

	It("returns an empty slice for an empty map", func() {
		Expect(SortedKeysByteValue(map[string][]byte{})).To(BeEmpty())
	})
})

var _ = Describe("SortedKeysBool", func() {
	It("returns keys in alphabetical order", func() {
		props := map[string]bool{"c": true, "a": true, "b": false}
		Expect(SortedKeysBool(props)).To(Equal([]string{"a", "b", "c"}))
	})

	It("returns an empty slice for an empty map", func() {
		Expect(SortedKeysBool(map[string]bool{})).To(BeEmpty())
	})
})

var _ = Describe("KeyValuePairs", func() {
	It("returns key=value lines, stripping leading whitespace", func() {
		raw := []byte("  foo=bar\n")
		pairs := KeyValuePairs(raw)
		Expect(pairs).To(ConsistOf("foo=bar"))
	})

	It("skips lines that start with #", func() {
		raw := []byte("# comment\nfoo=bar\n")
		pairs := KeyValuePairs(raw)
		Expect(pairs).To(ConsistOf("foo=bar"))
	})

	It("skips lines that start with !", func() {
		raw := []byte("! comment\nfoo=bar\n")
		pairs := KeyValuePairs(raw)
		Expect(pairs).To(ConsistOf("foo=bar"))
	})

	It("skips blank lines", func() {
		raw := []byte("\n\nfoo=bar\n\n")
		pairs := KeyValuePairs(raw)
		Expect(pairs).To(ConsistOf("foo=bar"))
	})

	It("returns an empty slice for a file with only comments", func() {
		raw := []byte("# just a comment\n")
		Expect(KeyValuePairs(raw)).To(BeEmpty())
	})

	It("preserves multiple key=value lines", func() {
		raw := []byte("a=1\nb=2\nc=3\n")
		Expect(KeyValuePairs(raw)).To(ConsistOf("a=1", "b=2", "c=3"))
	})
})

var _ = Describe("ReadReplaceEscapes", func() {
	It("replaces escaped spaces", func() {
		result := ReadReplaceEscapes([]string{`key=val\ ue`})
		Expect(result[0]).To(ContainSubstring("val ue"))
	})

	It("replaces escaped colons", func() {
		result := ReadReplaceEscapes([]string{`key=val\:ue`})
		Expect(result[0]).To(ContainSubstring("val:ue"))
	})

	It("replaces escaped equals signs", func() {
		result := ReadReplaceEscapes([]string{`key=val\=ue`})
		Expect(result[0]).To(ContainSubstring("val=ue"))
	})

	It("replaces escaped double quotes", func() {
		result := ReadReplaceEscapes([]string{`key=val\"ue`})
		Expect(result[0]).To(ContainSubstring(`val"ue`))
	})

	It("trims whitespace between key and = separator", func() {
		result := ReadReplaceEscapes([]string{"key  =  value"})
		Expect(result[0]).To(Equal("key=value"))
	})

	It("returns the input unchanged when there are no escapes", func() {
		result := ReadReplaceEscapes([]string{"foo=bar"})
		Expect(result[0]).To(Equal("foo=bar"))
	})

	It("passes through entries that have no = separator", func() {
		result := ReadReplaceEscapes([]string{"no-separator"})
		Expect(result[0]).To(Equal("no-separator"))
	})
})

var _ = Describe("DuplicateKeyIn", func() {
	It("returns empty string when there are no duplicates", func() {
		Expect(DuplicateKeyIn([]string{"a=1", "b=2", "c=3"})).To(BeEmpty())
	})

	It("returns the duplicated key when one is repeated", func() {
		Expect(DuplicateKeyIn([]string{"a=1", "b=2", "a=3"})).To(Equal("a"))
	})

	It("returns empty string for an empty list", func() {
		Expect(DuplicateKeyIn([]string{})).To(BeEmpty())
	})

	It("returns the first duplicate seen when multiple are duplicated", func() {
		result := DuplicateKeyIn([]string{"a=1", "b=2", "a=3", "b=4"})
		Expect(result).To(Equal("a"))
	})

	It("treats keys with escaped equals as distinct from each other", func() {
		kv := KeyValuePairs([]byte("aa\\=a=VAL\naa\\=b=VAL"))
		Expect(kv).To(HaveLen(2))
		Expect(DuplicateKeyIn(kv)).To(BeEmpty())
	})
})

var _ = Describe("DuplicateKeyInContent", func() {
	It("returns empty string when the properties file has no duplicate keys", func() {
		raw := []byte("a=1\nb=2\n")
		Expect(DuplicateKeyInContent(raw)).To(BeEmpty())
	})

	It("returns the duplicate key found in raw properties bytes", func() {
		raw := []byte("a=1\na=2\n")
		Expect(DuplicateKeyInContent(raw)).To(Equal("a"))
	})

	It("ignores comment lines when looking for duplicates", func() {
		raw := []byte("# comment\na=1\nb=2\n")
		Expect(DuplicateKeyInContent(raw)).To(BeEmpty())
	})
})

var _ = Describe("GetConfigExtraMount", func() {
	var extraMounts v1beta2.ExtraMountsType

	BeforeEach(func() {
		extraMounts = v1beta2.ExtraMountsType{
			ConfigMaps: []string{"my-cm" + JaasConfigSuffix},
			Secrets:    []string{"my-secret" + LoggingConfigSuffix},
		}
	})

	It("finds a configmap entry matching the suffix", func() {
		t, name, found := GetConfigExtraMount(extraMounts, JaasConfigSuffix)
		Expect(found).To(BeTrue())
		Expect(t).To(Equal("configmaps"))
		Expect(name).To(Equal("my-cm" + JaasConfigSuffix))
	})

	It("finds a secret entry matching the suffix", func() {
		t, name, found := GetConfigExtraMount(extraMounts, LoggingConfigSuffix)
		Expect(found).To(BeTrue())
		Expect(t).To(Equal("secrets"))
		Expect(name).To(Equal("my-secret" + LoggingConfigSuffix))
	})

	It("returns not-found when no entry matches the suffix", func() {
		_, _, found := GetConfigExtraMount(extraMounts, "-unknown-suffix")
		Expect(found).To(BeFalse())
	})

	It("returns empty strings when not found", func() {
		t, name, found := GetConfigExtraMount(extraMounts, "-unknown-suffix")
		Expect(found).To(BeFalse())
		Expect(t).To(BeEmpty())
		Expect(name).To(BeEmpty())
	})

	It("returns not-found for empty extra mounts", func() {
		_, _, found := GetConfigExtraMount(v1beta2.ExtraMountsType{}, JaasConfigSuffix)
		Expect(found).To(BeFalse())
	})
})

var _ = Describe("GetJaasConfigExtraMountPath", func() {
	It("returns the login.config mount path when a jaas-config secret is present", func() {
		mounts := v1beta2.ExtraMountsType{
			Secrets: []string{"my-secret" + JaasConfigSuffix},
		}
		path, found := GetJaasConfigExtraMountPath(mounts)
		Expect(found).To(BeTrue())
		Expect(path).To(Equal("/amq/extra/secrets/my-secret" + JaasConfigSuffix + "/login.config"))
	})

	It("returns the login.config mount path when a jaas-config configmap is present", func() {
		mounts := v1beta2.ExtraMountsType{
			ConfigMaps: []string{"my-cm" + JaasConfigSuffix},
		}
		path, found := GetJaasConfigExtraMountPath(mounts)
		Expect(found).To(BeTrue())
		Expect(path).To(Equal("/amq/extra/configmaps/my-cm" + JaasConfigSuffix + "/login.config"))
	})

	It("returns not-found when no jaas-config entry is present", func() {
		mounts := v1beta2.ExtraMountsType{
			Secrets: []string{"my-secret" + LoggingConfigSuffix},
		}
		path, found := GetJaasConfigExtraMountPath(mounts)
		Expect(found).To(BeFalse())
		Expect(path).To(BeEmpty())
	})
})

var _ = Describe("GetLoggingConfigExtraMountPath", func() {
	It("returns the logging.properties mount path when a logging-config secret is present", func() {
		mounts := v1beta2.ExtraMountsType{
			Secrets: []string{"my-secret" + LoggingConfigSuffix},
		}
		path, found := GetLoggingConfigExtraMountPath(mounts)
		Expect(found).To(BeTrue())
		Expect(path).To(Equal("/amq/extra/secrets/my-secret" + LoggingConfigSuffix + "/logging.properties"))
	})

	It("returns not-found when no logging-config entry is present", func() {
		mounts := v1beta2.ExtraMountsType{}
		_, found := GetLoggingConfigExtraMountPath(mounts)
		Expect(found).To(BeFalse())
	})
})

var _ = Describe("HasExtraMounts", func() {
	It("returns false when both configmaps and secrets are empty", func() {
		Expect(HasExtraMounts(v1beta2.ExtraMountsType{})).To(BeFalse())
	})

	It("returns true when configmaps are present", func() {
		Expect(HasExtraMounts(v1beta2.ExtraMountsType{ConfigMaps: []string{"my-cm"}})).To(BeTrue())
	})

	It("returns true when secrets are present", func() {
		Expect(HasExtraMounts(v1beta2.ExtraMountsType{Secrets: []string{"my-secret"}})).To(BeTrue())
	})
})

var _ = Describe("AssertSyntaxOkOnLoginConfigData", func() {
	validJaasConfig := []byte(`PropertiesLogin {
  org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule required
    reload=true;
};
`)

	BeforeEach(func() {
		loginConfigSyntaxMatcher = nil
	})

	It("returns nil for a syntactically valid JAAS login.config", func() {
		result := AssertSyntaxOkOnLoginConfigData(validJaasConfig, "my-secret", "")
		Expect(result).To(BeNil())
	})

	It("returns a condition for a syntactically invalid login.config", func() {
		invalid := []byte("this is not valid jaas config syntax")
		result := AssertSyntaxOkOnLoginConfigData(invalid, "my-secret", "ctx")
		Expect(result).NotTo(BeNil())
		Expect(result.Status).To(Equal(metav1.ConditionFalse))
		Expect(result.Reason).To(Equal(v1beta2.ValidConditionFailedExtraMountReason))
	})

	It("includes the secret name in the invalid condition message", func() {
		invalid := []byte("bad content")
		result := AssertSyntaxOkOnLoginConfigData(invalid, "named-secret", "prefix")
		Expect(result).NotTo(BeNil())
		Expect(result.Message).To(ContainSubstring("named-secret"))
	})
})

var _ = Describe("AssertInstanceCounts", func() {
	It("returns nil when all counts are exactly 1", func() {
		counts := map[string]int{JaasConfigSuffix: 1, LoggingConfigSuffix: 1}
		Expect(AssertInstanceCounts(counts, "Spec.ExtraMounts,")).To(BeNil())
	})

	It("returns a condition when a count exceeds 1", func() {
		counts := map[string]int{JaasConfigSuffix: 2}
		result := AssertInstanceCounts(counts, "Spec.ExtraMounts,")
		Expect(result).NotTo(BeNil())
		Expect(result.Status).To(Equal(metav1.ConditionFalse))
		Expect(result.Message).To(ContainSubstring(JaasConfigSuffix))
		Expect(result.Message).To(ContainSubstring("Spec.ExtraMounts,"))
	})

	It("returns nil for an empty map", func() {
		Expect(AssertInstanceCounts(map[string]int{}, "Spec.ExtraMounts,")).To(BeNil())
	})
})

var _ = Describe("AssertConfigMapContainsKey", func() {
	It("returns nil when the key is present", func() {
		cm := corev1.ConfigMap{
			ObjectMeta: metav1.ObjectMeta{Name: "my-cm"},
			Data:       map[string]string{JaasConfigKey: "some-content"},
		}
		Expect(AssertConfigMapContainsKey(cm, JaasConfigKey, "")).To(BeNil())
	})

	It("returns a condition when the key is absent", func() {
		cm := corev1.ConfigMap{
			ObjectMeta: metav1.ObjectMeta{Name: "my-cm"},
			Data:       map[string]string{},
		}
		result := AssertConfigMapContainsKey(cm, JaasConfigKey, "ctx")
		Expect(result).NotTo(BeNil())
		Expect(result.Status).To(Equal(metav1.ConditionFalse))
		Expect(result.Message).To(ContainSubstring("my-cm"))
		Expect(result.Message).To(ContainSubstring(JaasConfigKey))
	})
})

var _ = Describe("AssertNoDupKeyInProperties", func() {
	It("returns nil when the secret has no duplicate keys", func() {
		secret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: "my-secret"},
			Data: map[string][]byte{
				BrokerPropertiesName: []byte("a=1\nb=2\n"),
			},
		}
		Expect(AssertNoDupKeyInProperties(secret, "")).To(BeNil())
	})

	It("returns a condition when a .properties entry has a duplicate key", func() {
		secret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: "my-secret"},
			Data: map[string][]byte{
				BrokerPropertiesName: []byte("a=1\na=2\n"),
			},
		}
		result := AssertNoDupKeyInProperties(secret, "ctx")
		Expect(result).NotTo(BeNil())
		Expect(result.Status).To(Equal(metav1.ConditionFalse))
		Expect(result.Message).To(ContainSubstring("my-secret"))
		Expect(result.Message).To(ContainSubstring("a"))
	})

	It("skips keys that start with the unchecked prefix", func() {
		secret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: "my-secret"},
			Data: map[string][]byte{
				UncheckedPrefix + BrokerPropertiesName: []byte("a=1\na=2\n"),
			},
		}
		Expect(AssertNoDupKeyInProperties(secret, "")).To(BeNil())
	})

	It("skips keys that do not end with .properties", func() {
		secret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: "my-secret"},
			Data: map[string][]byte{
				"login.config": []byte("a=1\na=2\n"),
			},
		}
		Expect(AssertNoDupKeyInProperties(secret, "")).To(BeNil())
	})
})

var _ = Describe("AssertSecretContainsKey", func() {
	It("returns nil when the key is present in a regular secret", func() {
		secret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: "my-secret"},
			Data:       map[string][]byte{JaasConfigKey: []byte("content")},
		}
		Expect(AssertSecretContainsKey(secret, JaasConfigKey, "")).To(BeNil())
	})

	It("returns a condition when the key is absent from a regular secret", func() {
		secret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: "my-secret"},
			Data:       map[string][]byte{},
		}
		result := AssertSecretContainsKey(secret, JaasConfigKey, "ctx")
		Expect(result).NotTo(BeNil())
		Expect(result.Status).To(Equal(metav1.ConditionFalse))
		Expect(result.Reason).To(Equal(v1beta2.ValidConditionFailedExtraMountReason))
		Expect(result.Message).To(ContainSubstring("my-secret"))
	})

	It("returns nil for a valid cert secret (name ends with -ptls)", func() {
		secret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: "my-secret" + certutil.Cert_provided_secret_suffix},
			Data:       map[string][]byte{},
		}
		Expect(AssertSecretContainsKey(secret, "tls.crt", "")).To(BeNil())
	})

	It("returns a condition with invalid cert reason for an invalid cert secret", func() {
		secret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{
				Name:        "my-secret",
				Annotations: map[string]string{certutil.Cert_annotation_key: "my-issuer"},
			},
			Data: map[string][]byte{"only-one-key": []byte("value")},
		}
		result := AssertSecretContainsKey(secret, "tls.crt", "ctx")
		Expect(result).NotTo(BeNil())
		Expect(result.Reason).To(Equal(v1beta2.ValidConditionInvalidCertSecretReason))
	})
})

var _ = Describe("AssertSecretContainsOneOf", func() {
	It("returns nil when one of the required keys is present", func() {
		secret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: "my-secret"},
			Data:       map[string][]byte{"tls.key": []byte("value")},
		}
		Expect(AssertSecretContainsOneOf(secret, []string{"tls.crt", "tls.key"}, "")).To(BeNil())
	})

	It("returns a condition when none of the required keys is present", func() {
		secret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: "my-secret"},
			Data:       map[string][]byte{"other-key": []byte("value")},
		}
		result := AssertSecretContainsOneOf(secret, []string{"tls.crt", "tls.key"}, "ctx")
		Expect(result).NotTo(BeNil())
		Expect(result.Status).To(Equal(metav1.ConditionFalse))
		Expect(result.Reason).To(Equal(v1beta2.ValidConditionFailedExtraMountReason))
		Expect(result.Message).To(ContainSubstring("my-secret"))
	})

	It("returns nil for a valid cert secret identified by -ptls suffix", func() {
		secret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: "my-secret" + certutil.Cert_provided_secret_suffix},
			Data:       map[string][]byte{},
		}
		Expect(AssertSecretContainsOneOf(secret, []string{"tls.crt"}, "")).To(BeNil())
	})

	It("returns a condition with invalid cert reason for an invalid cert secret", func() {
		secret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{
				Name:        "my-secret",
				Annotations: map[string]string{certutil.Cert_annotation_key: "my-issuer"},
			},
			Data: map[string][]byte{"only-one-key": []byte("value")},
		}
		result := AssertSecretContainsOneOf(secret, []string{"tls.crt", "tls.key"}, "ctx")
		Expect(result).NotTo(BeNil())
		Expect(result.Reason).To(Equal(v1beta2.ValidConditionInvalidCertSecretReason))
	})
})
