apiVersion: broker.arkmq.org/v1beta2
kind: Broker
metadata:
  name: my-broker-props-address
spec:
  brokerProperties:
   - "# anycast, consumers compete"
   - addressConfigurations."APP.JOBS".routingTypes=ANYCAST
   - addressConfigurations."APP.JOBS".queueConfigs."APP.JOBS".routingType=ANYCAST
   - "# mulitcast, consumers see all messages"
   - addressConfigurations."APP.COMMANDS".routingTypes=MULTICAST
   - "# allow delete (this is the source of truth)"
   - addressSettings."APP.#".configDeleteAddresses=FORCE
   - addressSettings."APP.#".configDeleteQueues=FORCE
